### ISSUE TITLE
ArtPollReplyPacket read EstaCode bug

### ISSUE THREAD

**Issue by semyonpark** [HakanL/ACN#7]
Please check the ArtPollReplyPacket.cs, method ReadData. EstaCode could be read as EstaCode =  data.ReadInt16();

**Comment by HakanL** [comment]
Are you sure? All the other properties in that packet are read in "network order". Do you have any documentation that shows how it should be read? This is just a fork from an existing package so I haven't authored this particular piece of code.

**Comment by semyonpark** [comment]
https://art-net.org.uk/structure/discovery-packets/artpollreply/
"ESTA" field - low byte first like "Port" field

**Comment by HakanL** [comment]
Thanks for the details, make sense, just add that they mixed lo/hi and hi/lo in their spec. But I can see that it's correct in the code for writing a packet. It's been fixed now. BTW, I would probably recommend my other ArtNet library that is a stripped down version of the original ACN, for .NET Standard, and I publish it to NuGet: https://github.com/HakanL/Haukcode.ArtNet

**Comment by semyonpark** [comment]
Thanks for your time and effort.
